version: '3'
services:
  bot:
    build:
      context: .
    ## define your token HERE
    command: sh -c "rm -rf target && cargo build --release && ./discord_bot"
    environment:
      - DISCORD_TOKEN= ##TOKEN HERE##
